import "./globals.css";
import localFont from "@next/font/local";
import { Inter } from "next/font/google";
import { Session } from "next-auth";
import { headers } from "next/headers";
import { api } from "@/utils/api";
import AuthContext from "@/components/auth-context";

async function getSession(cookie: string): Promise<Session> {
  const response = await api(`/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = localFont({
  src: [
    {
      path: "../../public/fonts/lato/Lato-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/lato/Lato-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-lato",
});

const montserrat = localFont({
  src: [
    {
      path: "../../public/fonts/montserrat/Montserrat-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/montserrat/Montserrat-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-montserrat",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get("cookie") ?? "");
  console.log(session, "ROOT LAYOUT SESSION");
  return (
    <html lang="en" className={`${lato.variable} ${montserrat.variable}`}>
      <body>
        <AuthContext session={session}>{children}</AuthContext>
      </body>
    </html>
  );
}
