"use client";
import NavBar from "@/components/navbar";
import Link from "@/components/overriden/link";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <p>Loading...</p>;
  }

  if (status === "unauthenticated") {
    return <p>Access Denied</p>;
  }

  return (
    <div className="h-full w-full flex flex-row pt-6 pr-6 bg-[#DDD]">
      <div className="w-1/3 flex pb-6 px-10">
        <NavBar />
      </div>
      {children}
    </div>
  );
}
